os: linux
dist: xenial
language: cpp
script:
  - git fetch --tags --unshallow || if [ $? -eq 128 ]; then true; else false; fi
  - git rev-list --count HEAD
  - bash -x build.sh
deploy:
  provider: releases
  token: $ACCESS_TOKEN
  file_glob: true
  file:
    - build/Prusa-CW1*-Firmware-*.hex
  skip_cleanup: true
  draft: true
  prerelease: true
  on:
    tags: true
